import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CustomButton from '../components/./customButton/button'
import CustomRadioButton from '../components/customRadioButton/radioButton'
import {CheckButton} from "../components/customCheckButton/checkButton";

export default function Home() {
    return (
        <div>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
            </div>

            <div>
                <CustomButton text={'Создать игру'} disabled={false}/>
                <CustomButton text={'Создать игру'} disabled={false}/>
                <CustomButton text={'Создать игру'} disabled={false}/>
                <CustomButton text={'Создать игру'} disabled={true}/>
                <CustomRadioButton text={'Романа Мстиславича'} disabled={false}/>
                <CustomRadioButton text={'Романа Мстиславича'} disabled={false}/>
                <CustomRadioButton text={'Романа Мстиславича'} disabled={false}/>
                <CustomRadioButton text={'Романа Мстиславича'} disabled={true}/>
                <CheckButton disabled={false}/>
                <CheckButton disabled={false}/>
                <CheckButton disabled={false}/>
                <CheckButton disabled={true}/>
            </div>
        </div>
    )
}
